// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApqrHz_xGklwCYehY2QSyqZSYbb5Lomx4',
    appId: '1:176685015524:web:cc6f7824fab4ade21e67f1',
    messagingSenderId: '176685015524',
    projectId: 'acthubtraining',
    authDomain: 'acthubtraining.firebaseapp.com',
    storageBucket: 'acthubtraining.appspot.com',
    measurementId: 'G-5F17LJEV78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUpSkL3JLMEn8lRXBoTCIctj5JwNlIo2Y',
    appId: '1:176685015524:android:df510706c1506dac1e67f1',
    messagingSenderId: '176685015524',
    projectId: 'acthubtraining',
    storageBucket: 'acthubtraining.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjziChCnMPolwAm0i_UG0gt5Epu-men6I',
    appId: '1:176685015524:ios:346def61ef076a901e67f1',
    messagingSenderId: '176685015524',
    projectId: 'acthubtraining',
    storageBucket: 'acthubtraining.appspot.com',
    iosClientId: '176685015524-ju6hjcsvoddlb8meh009g0bo3mt1pr72.apps.googleusercontent.com',
    iosBundleId: 'com.example.actHubTraining1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjziChCnMPolwAm0i_UG0gt5Epu-men6I',
    appId: '1:176685015524:ios:346def61ef076a901e67f1',
    messagingSenderId: '176685015524',
    projectId: 'acthubtraining',
    storageBucket: 'acthubtraining.appspot.com',
    iosClientId: '176685015524-ju6hjcsvoddlb8meh009g0bo3mt1pr72.apps.googleusercontent.com',
    iosBundleId: 'com.example.actHubTraining1',
  );
}
